//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
[assembly: System.Reflection.AssemblyInformationalVersion("1.8.2.0-f55187f")]
=======
[assembly: System.Reflection.AssemblyInformationalVersion("1.8.3.0-7286b14")]
>>>>>>> refs/remotes/origin/Improve-Feed_Twitter-notify


